### ISSUE TITLE
(Feature Request) GROMACS crashes when higher TEMP used

### ISSUE THREAD

**Issue by dkozuch** [invemichele/plumed2#4]
I'm attempting an extreme temperature ranges 170 K - 600 K. If I use a system temperature of 300 K, everything runs fine. However, if I use a system temperature of 400 K, the system runs fine at the beginning (when there is no bias) but explodes after 100 ps (exactly when the bias starts). 

I assume this is because the bias required to move from 400 K to 170 K is so high that an instability is reached. Is there some way to limit the bias potential so the system doesn't explode?

Sample plumed file below and example attached.
[test.tar.gz](https://github.com/invemichele/plumed2/files/5374690/test.tar.gz)

```
ene: ENERGY
vol: VOLUME

ECV_MULTITHERMAL_MULTIBARIC ...
  LABEL=mtp
  ARG=ene,vol
  TEMP=400
  MIN_TEMP=170
  MAX_TEMP=600
  PRESSURE=0.06022140857*2000 #2 kbar
  MIN_PRESSURE=0.06022140857  #1 bar
  MAX_PRESSURE=0.06022140857*4000 #4 kbar
  CUT_CORNER=500,0.06022140857,600,0.06022140857*2000
... ECV_MULTITHERMAL_MULTIBARIC

opes: OPES_EXPANDED ARG=mtp.* FILE=DeltaF.data PACE=500 OBSERVATION_STEPS=100 PRINT_STRIDE=100

PRINT STRIDE=500 FILE=COLVAR ARG=*
```

Best,
Dan

**Comment by invemichele** [comment]
Hi Dan,
this is indeed the part of the method where I expect more improvement can be made: the initial DeltaFs guess.

As of now there is a BARRIER keyword in the ECVs that you can use to avoid the initial bias being too strong. However, while it is very handy for the multiumbrella target (where it is somehow easy to guess the height of the barrier to be overcome), I wouldn't suggest to use it in your case.

If you have extra info about your system you can manually set the initial DeltaFs, by storing them in the proper order on a file an trigger a restart from it.
We haven't come up yet with a better automatic way to get a good initial guess, independently of the initial temperature... I'm open to suggestions!

In my experience due to how the DeltaFs are calculated (Eq. 9 of the paper), it is much faster to correct the initial guess if the values are overestimated (thus bias greater than really needed), while if the initial DeltaFs are underestimated, then the system might never visit that region (not enough bias), and never change the initial bad estimate. This is also the reason why we are not using cumulant expansion to guess the initial DeltaFs. The drawback is of course that if we exaggerate the system explodes, but at least does it at the very beginning, no time wasted.
Here is how the DeltaFs estimates look like for the chignolin in the paper:
![chignolin_DeltaF](https://user-images.githubusercontent.com/14904699/95979301-b6e07000-0e1b-11eb-9097-c5dff52f23a1.gif)

**Comment by dkozuch** [comment]
Thanks for the extra info! My only suggestion at this point is a little hacky, but maybe there could be a keyword (like SOFTEN, or something) that could be included in the function that would trigger a less aggressive potential at the beginning of the simulation. I expect to run my simulations for a very long time, so quick convergence of the bias potential is nice, but not necessarily more important than being able to set higher velocities.

**Comment by invemichele** [comment]
Ok, I see. I do have some ideas about this, I think we should discuss it also with @PabloPiaggi. I will send you an email
